import type { CardDef, HeroDef, HeroId } from './types'
import { COMPANIONS, COMPANION_CARDS, BUILD_RELICS, ROAD_EVENTS } from './companions'

export const HEROES: Record<HeroId, HeroDef> = {
  ...COMPANIONS,
  warden: {
    id: 'warden',
    name: 'Бран',
    role: 'Страж',
    title: 'Держать строй',
    hp: 48,
    color: '#b57539',
    passive: 'Каждая его карта даёт ему ещё 2 защиты.',
    cards: ['slash', 'shield', 'bash'],
  },
  ranger: {
    id: 'ranger',
    name: 'Лина',
    role: 'Следопыт',
    title: 'Бить точно',
    hp: 36,
    color: '#4d8567',
    passive: 'Первая её атака в ход наносит ещё 3 урона.',
    cards: ['shot', 'mark', 'volley'],
  },
  mage: {
    id: 'mage',
    name: 'Эли',
    role: 'Маг',
    title: 'Менять правила',
    hp: 30,
    color: '#8470b0',
    passive: 'Каждое его заклинание даёт всему отряду 1 защиты.',
    cards: ['spark', 'frost', 'nova'],
  },
  rogue: {
    id: 'rogue',
    name: 'Рен',
    role: 'Плут',
    title: 'Побеждать хитростью',
    hp: 34,
    color: '#bd6973',
    passive: 'Его атаки по уязвимым врагам наносят ещё 3 урона.',
    cards: ['dagger', 'venom', 'feint'],
  },
  priest: {
    id: 'priest',
    name: 'Мира',
    role: 'Целитель',
    title: 'Вернуть надежду',
    hp: 36,
    color: '#c39743',
    passive: 'Её лечение восстанавливает ещё 2 здоровья.',
    cards: ['smite', 'mend', 'ward'],
  },
  bard: {
    id: 'bard',
    name: 'Том',
    role: 'Бард',
    title: 'Поймать ритм',
    hp: 35,
    color: '#478fa1',
    passive: 'После его карты отряд получает 1 защиты.',
    cards: ['note', 'inspire', 'chorus'],
  },
}

export const CARDS: CardDef[] = [
  ...COMPANION_CARDS,
  {
    id: 'slash',
    name: 'Удар мечом',
    hero: 'warden',
    kind: 'attack',
    cost: 1,
    target: 'enemy',
    damage: 9,
    text: 'Нанести 9 урона.',
  },
  {
    id: 'shield',
    name: 'Поднять щит',
    hero: 'warden',
    kind: 'skill',
    cost: 1,
    target: 'ally',
    block: 11,
    text: 'Дать герою 11 защиты на этот ход.',
  },
  {
    id: 'bash',
    name: 'Удар щитом',
    hero: 'warden',
    kind: 'attack',
    cost: 1,
    target: 'enemy',
    damage: 6,
    block: 5,
    text: '6 урона врагу. Страж получает 5 защиты.',
  },
  {
    id: 'rampart',
    name: 'Крепость',
    hero: 'warden',
    kind: 'skill',
    cost: 2,
    target: 'all',
    block: 8,
    text: 'Дать всем героям 8 защиты.',
  },
  {
    id: 'cleave',
    name: 'Широкий замах',
    hero: 'warden',
    kind: 'attack',
    cost: 2,
    target: 'all',
    damage: 11,
    text: 'Нанести всем врагам 11 урона.',
  },
  {
    id: 'challenge',
    name: 'Контрудар',
    hero: 'warden',
    kind: 'attack',
    cost: 1,
    target: 'enemy',
    damage: 7,
    block: 7,
    text: '7 урона. Страж получает 7 защиты.',
  },
  {
    id: 'shot',
    name: 'Точный выстрел',
    hero: 'ranger',
    kind: 'attack',
    cost: 1,
    target: 'enemy',
    damage: 10,
    text: 'Нанести 10 урона.',
  },
  {
    id: 'mark',
    name: 'Метка охотника',
    hero: 'ranger',
    kind: 'skill',
    cost: 0,
    target: 'enemy',
    vulnerable: 2,
    text: 'Уязвимость на 2 хода: атаки наносят на 50% больше.',
  },
  {
    id: 'volley',
    name: 'Залп',
    hero: 'ranger',
    kind: 'attack',
    cost: 2,
    target: 'all',
    damage: 9,
    text: 'Нанести всем врагам 9 урона.',
  },
  {
    id: 'quickshot',
    name: 'Быстрая стрела',
    hero: 'ranger',
    kind: 'attack',
    cost: 0,
    target: 'enemy',
    damage: 5,
    text: 'Нанести 5 урона без затрат энергии.',
  },
  {
    id: 'aim',
    name: 'Выждать момент',
    hero: 'ranger',
    kind: 'skill',
    cost: 0,
    target: 'self',
    draw: 2,
    text: 'Взять 2 карты. Исчезает до конца боя.',
    exhaust: true,
  },
  {
    id: 'pierce',
    name: 'Пробить броню',
    hero: 'ranger',
    kind: 'attack',
    cost: 1,
    target: 'enemy',
    damage: 13,
    text: '13 урона. Игнорирует защиту врага.',
  },
  {
    id: 'spark',
    name: 'Искра',
    hero: 'mage',
    kind: 'spell',
    cost: 1,
    target: 'enemy',
    damage: 11,
    text: 'Нанести 11 урона.',
  },
  {
    id: 'frost',
    name: 'Ледяной покров',
    hero: 'mage',
    kind: 'spell',
    cost: 1,
    target: 'ally',
    block: 10,
    draw: 1,
    text: '10 защиты герою. Взять 1 карту.',
  },
  {
    id: 'nova',
    name: 'Кольцо огня',
    hero: 'mage',
    kind: 'spell',
    cost: 2,
    target: 'all',
    damage: 12,
    text: 'Нанести всем врагам 12 урона.',
  },
  {
    id: 'channel',
    name: 'Поток маны',
    hero: 'mage',
    kind: 'spell',
    cost: 0,
    target: 'self',
    energy: 2,
    text: 'Получить 2 энергии. Исчезает до конца боя.',
    exhaust: true,
  },
  {
    id: 'meteor',
    name: 'Метеор',
    hero: 'mage',
    kind: 'spell',
    cost: 3,
    target: 'enemy',
    damage: 34,
    text: 'Нанести 34 урона.',
  },
  {
    id: 'arcane',
    name: 'Отголосок',
    hero: 'mage',
    kind: 'spell',
    cost: 1,
    target: 'enemy',
    damage: 7,
    draw: 2,
    text: '7 урона. Взять 2 карты.',
  },
  {
    id: 'dagger',
    name: 'Удар кинжалом',
    hero: 'rogue',
    kind: 'attack',
    cost: 1,
    target: 'enemy',
    damage: 8,
    text: 'Нанести 8 урона.',
  },
  {
    id: 'venom',
    name: 'Отравленный клинок',
    hero: 'rogue',
    kind: 'attack',
    cost: 1,
    target: 'enemy',
    damage: 4,
    poison: 5,
    text: '4 урона и 5 яда. Яд обходит защиту в конце хода.',
  },
  {
    id: 'feint',
    name: 'Ложный выпад',
    hero: 'rogue',
    kind: 'skill',
    cost: 0,
    target: 'enemy',
    vulnerable: 1,
    draw: 1,
    text: '1 ход уязвимости. Взять 1 карту.',
  },
  {
    id: 'toxin',
    name: 'Густой яд',
    hero: 'rogue',
    kind: 'skill',
    cost: 1,
    target: 'enemy',
    poison: 9,
    text: 'Наложить 9 яда.',
  },
  {
    id: 'ambush',
    name: 'Засадный удар',
    hero: 'rogue',
    kind: 'attack',
    cost: 2,
    target: 'enemy',
    damage: 22,
    text: 'Нанести 22 урона.',
  },
  {
    id: 'evade',
    name: 'Ускользнуть',
    hero: 'rogue',
    kind: 'skill',
    cost: 0,
    target: 'self',
    block: 7,
    draw: 1,
    text: '7 защиты плуту. Взять 1 карту.',
  },
  {
    id: 'smite',
    name: 'Свет',
    hero: 'priest',
    kind: 'spell',
    cost: 1,
    target: 'enemy',
    damage: 8,
    text: 'Нанести 8 урона.',
  },
  {
    id: 'mend',
    name: 'Перевязка',
    hero: 'priest',
    kind: 'skill',
    cost: 1,
    target: 'ally',
    heal: 6,
    text: 'Восстановить герою 6 здоровья. Исчезает до конца боя.',
    exhaust: true,
  },
  {
    id: 'ward',
    name: 'Оберег',
    hero: 'priest',
    kind: 'spell',
    cost: 1,
    target: 'ally',
    block: 12,
    text: 'Дать герою 12 защиты.',
  },
  {
    id: 'renew',
    name: 'Второе дыхание',
    hero: 'priest',
    kind: 'spell',
    cost: 2,
    target: 'all',
    heal: 5,
    text: 'Восстановить всем живым героям 5 здоровья. Исчезает.',
    exhaust: true,
  },
  {
    id: 'sun',
    name: 'Солнечное копьё',
    hero: 'priest',
    kind: 'spell',
    cost: 2,
    target: 'enemy',
    damage: 20,
    text: 'Нанести 20 урона.',
  },
  {
    id: 'bless',
    name: 'Благословение',
    hero: 'priest',
    kind: 'spell',
    cost: 0,
    target: 'ally',
    block: 5,
    draw: 1,
    text: '5 защиты герою. Взять 1 карту.',
  },
  {
    id: 'note',
    name: 'Резкая нота',
    hero: 'bard',
    kind: 'attack',
    cost: 1,
    target: 'enemy',
    damage: 8,
    draw: 1,
    text: '8 урона. Взять 1 карту.',
  },
  {
    id: 'inspire',
    name: 'Вдохновение',
    hero: 'bard',
    kind: 'skill',
    cost: 0,
    target: 'self',
    energy: 1,
    draw: 1,
    text: '1 энергия и 1 карта. Исчезает до конца боя.',
    exhaust: true,
  },
  {
    id: 'chorus',
    name: 'Общий ритм',
    hero: 'bard',
    kind: 'skill',
    cost: 1,
    target: 'all',
    block: 6,
    text: 'Дать всем героям 6 защиты.',
  },
  {
    id: 'ballad',
    name: 'Походная песня',
    hero: 'bard',
    kind: 'skill',
    cost: 1,
    target: 'all',
    heal: 3,
    text: 'Восстановить всем живым героям 3 здоровья. Исчезает.',
    exhaust: true,
  },
  {
    id: 'encore',
    name: 'На бис',
    hero: 'bard',
    kind: 'skill',
    cost: 0,
    target: 'self',
    draw: 3,
    text: 'Взять 3 карты. Исчезает до конца боя.',
    exhaust: true,
  },
  {
    id: 'discord',
    name: 'Диссонанс',
    hero: 'bard',
    kind: 'attack',
    cost: 1,
    target: 'all',
    damage: 6,
    vulnerable: 1,
    text: 'Всем врагам: 6 урона и 1 ход уязвимости.',
  },
]
export const CARD_MAP = Object.fromEntries(CARDS.map((c) => [c.id, c])) as Record<string, CardDef>
export const STARTERS: HeroId[] = ['warden', 'ranger', 'mage', 'alchemist', 'duelist', 'oracle']
export const STARTER_PARTIES: Record<string, HeroId[]> = {
  warden: ['warden', 'ranger', 'priest'],
  ranger: ['ranger', 'warden', 'rogue'],
  mage: ['mage', 'warden', 'bard'],
  alchemist: ['alchemist', 'warden', 'rogue'],
  duelist: ['duelist', 'oracle', 'priest'],
  oracle: ['oracle', 'alchemist', 'bard'],
}
export const STARTER_RELIC: Record<string, string> = {
  warden: 'lantern',
  ranger: 'satchel',
  mage: 'hourglass',
  alchemist: 'vial',
  duelist: 'lantern',
  oracle: 'hourglass',
}
export const RELICS = [
  ...BUILD_RELICS,
  {
    id: 'lantern',
    name: 'Походный фонарь',
    icon: 'sun',
    text: 'В начале каждого боя отряд получает 4 защиты.',
  },
  {
    id: 'flask',
    name: 'Дорожная фляга',
    icon: 'heart',
    text: 'После победы каждый живой герой восстанавливает 5 здоровья.',
  },
  {
    id: 'whetstone',
    name: 'Точильный камень',
    icon: 'sword',
    text: 'Все карты с уроном наносят ещё 2 урона.',
  },
  {
    id: 'hourglass',
    name: 'Песочные часы',
    icon: 'spark',
    text: 'В первом ходу каждого боя +1 энергия.',
  },
  {
    id: 'quiver',
    name: 'Запасной колчан',
    icon: 'cards',
    text: 'В начале каждого хода взять ещё 1 карту.',
  },
  {
    id: 'cloak',
    name: 'Плащ дозорного',
    icon: 'shield',
    text: 'В начале каждого хода все герои получают 2 защиты.',
  },
  {
    id: 'herbs',
    name: 'Полевые травы',
    icon: 'leaf',
    text: 'Любое лечение восстанавливает ещё 2 здоровья.',
  },
  { id: 'vial', name: 'Змеиный настой', icon: 'drop', text: 'Карты с ядом накладывают ещё 2 яда.' },
  { id: 'coin', name: 'Счастливая монета', icon: 'coin', text: 'После каждой победы +10 монет.' },
  {
    id: 'satchel',
    name: 'Сумка разведчика',
    icon: 'cards',
    text: 'В первом ходу каждого боя взять ещё 2 карты.',
  },
  {
    id: 'ember',
    name: 'Тёплый уголь',
    icon: 'fire',
    text: 'Каждая третья сыгранная карта наносит всем врагам 3 урона.',
  },
  {
    id: 'banner',
    name: 'Знамя отряда',
    icon: 'flag',
    text: 'В начале боя каждый живой герой восстанавливает 3 здоровья.',
  },
]
export const RELIC_MAP = Object.fromEntries(RELICS.map((r) => [r.id, r])) as Record<
  string,
  (typeof RELICS)[number]
>
export const AREAS = [
  {
    name: 'Зелёный тракт',
    tag: 'Лес и старые дороги',
    boss: 'Хранитель моста',
    color: '#4c8469',
    description: 'Тропа под соснами, первые стычки и время найти свой ритм.',
  },
  {
    name: 'Старые руины',
    tag: 'Камень и забытые залы',
    boss: 'Каменный дозорный',
    color: '#8371a3',
    description: 'Сломанные арки, древние механизмы и более опасные противники.',
  },
  {
    name: 'Высокий перевал',
    tag: 'Ветер и горные тропы',
    boss: 'Горный дракон',
    color: '#46859b',
    description: 'Последний подъём. Всё, что вы собрали, пригодится здесь.',
  },
]
export const EVENTS = [
  {
    name: 'Заброшенная часовня',
    text: 'На каменном столе лежит амулет. Рядом — чистая вода. Здесь можно задержаться лишь ненадолго.',
    a: 'Выпить из источника',
    aText: 'Весь отряд восстанавливает 12 здоровья.',
    b: 'Забрать амулет',
    bText: 'Случайная реликвия. Каждый герой теряет 7 здоровья.',
  },
  {
    name: 'Попутчик',
    text: 'У костра сидит путешественник. В обмен на припасы он готов поделиться знаниями.',
    a: 'Помочь с припасами',
    aText: 'Заплатить 25 монет. Улучшить две случайные карты.',
    b: 'Выслушать историю',
    bText: 'Получить 15 монет. Продолжить путь.',
  },
  {
    name: 'Тайник у дороги',
    text: 'Под корнями спрятан тяжёлый сундук. Замок покрыт тонкими иглами.',
    a: 'Открыть сундук',
    aText: 'Получить 50 монет. Первый герой теряет 10 здоровья.',
    b: 'Искать безопасный проход',
    bText: 'Весь отряд получает 4 здоровья.',
  },
  ...ROAD_EVENTS,
]
export const KIND_LABEL = {
  battle: 'Стычка',
  elite: 'Элита',
  rest: 'Привал',
  event: 'Встреча',
  shop: 'Торговец',
  boss: 'Босс',
}
